<?php
/**
 * @file
 * A block that displays collection information when the user performs a blank search
 */

/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
function flvc_custom_display_help($path, $arg) {
  switch ($path) {
    case "admin/help#flvc_custom_display":
      return '<p>' . t("Displays collection information related to an empty search") . '</p>';
      break;
  }
}

/**
* Implements hook_block_info().
*/
function flvc_custom_display_block_info() {
  $blocks['flvc_custom_display'] = array(
    'info' => t('Collection Information in Search'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}

/**
* Get Collection Object function.
*
* Get the collection objectId from the URL and retrive the object from the Fedora repository
*
* @return
*   The collection object
*/
function flvc_custom_display_get_collection_information(){
  
  global $base_url;

  $banner = '';
  $exists = false;
  $desc_text = false;
  $collection_id = NULL;
  $collection = array();
  $collection['name'] = 'Not a Collection';
  $collection['base_url'] = $base_url;

  if (isset($_GET['collection']))
  {
    $collection_id = $_GET['collection'];
    $collection['id'] = $collection_id;
  }

  if ($collection_id)
  {
    // load object and get the collection name
    $collection_object = islandora_object_load($collection_id);
    $collection['name'] = $collection_object->label;

    //create DC datastream URL
    $collection['dc_url'] = $base_url . '/islandora/object/' . $collection_id . '/datastream/DC/';

    //retrieve the DC databsteam
    $dc = file_get_contents($collection['dc_url']);

    //convert DC into an object
    $collection['dc_object'] = DublinCore::importFromXMLString($dc);

    //if the Dublin Core exists, retrieve the collection name
    if($collection['dc_object'])
    {
      $dc_object_array = $collection['dc_object']->asArray();
    }
   
    //create DESC-TEXT datastream URL
    $collection['description_url'] = $base_url . '/islandora/object/' . $collection_id . '/datastream/DESC-TEXT/';
 
    //Check if the DESC-TEXT datastream exists
    $datastream_headers = @get_headers($collection['description_url']);
    if($datastream_headers[0] == 'HTTP/1.1 404 Not Found') {
      $desc_exists = false;
    }
    else {
      $desc_exists = true;
    }    

    //Try to retrieve the description text datastream
    if($desc_exists)
    {
      //$desc_text = @file_get_contents($collection['description_url']);
      $desc_text = $collection_object['DESC-TEXT']->content;
    }

    if ($desc_text)
    {
      $collection['description_text'] = $desc_text;
    }
    else
    {
      $collection['description_text'] = '&nbsp;';
    }

    //create BANNER datastream URL
    $collection['banner_url'] = $base_url . '/islandora/object/' . $collection_id . '/datastream/BANNER/view';
 
    //Check if the BANNER datastream exists
    $datastream_headers = @get_headers($collection['banner_url']);
    if(strpos($datastream_headers[0], '200') === false) {
      $collection['banner_exists'] = false;       
    }
    else {
      $collection['banner_exists'] = true;       
    }
}

  return $collection;
}

/**
* Implements hook_block_view().
*
* Prepares the contents of the block.
*/
function flvc_custom_display_block_view($delta = '') {
  switch($delta){
    case 'flvc_custom_display':
      if(user_access('access content')){
        //Use custom function to retrieve collection information.
        $collection_info = flvc_custom_display_get_collection_information();
     
        if ($collection_info) { //Found collection, send to theme.
  
          $search_form =       

            '<div id="local-search-container">
              <h2 class="local-collection-search-title">Search this Collection</h2>
              <form id="local-collection-search-form" accept-charset="UTF-8" onsubmit="return makeURL(\'local-collection-search-form\');" method="get" action="#">
                <div class="form-item">
                  <input class="search-input-text" type="text" maxlength="128" name="islandora_simple_search_query" />
                  <input type="submit" name="submit" value="search"  class="form-submit" />
                </div>
                  <input type="hidden" name="islandora_simple_collection" value="' . $collection_info['id'] . '">
                  <input type="hidden" name="base_url" value="' . $collection_info['base_url'] . '">
                </form>
             </div>';

          if($collection_info['banner_exists'])
          { 
            $formatted_banner = theme('image', array('path' => $collection_info['banner_url']));
          }
          else
          {
            $formatted_banner = t($collection_info['name']);
          }     

          $formatted_description = t($collection_info['description_text']);
           
          if($collection_info['banner_exists'])
          {
            $block['content'] = '<p>' . $formatted_banner . '</p>' . $search_form . $formatted_description;
          }
          else
          {
            $block['subject'] = $formatted_banner;
            $block['content'] = $search_form . $formatted_description;
          }     
        } 
        else {
          //No Collection Info
          $block['content'] = t('Unable to retrieve collection information');
        }
      }
    return $block;
  }
}
